server:
  port: 8080

spring:
  application:
    name: ai-tourism
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources/static
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ai_tourism?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379

langchain4j:
  open-ai:
    chat-model:
      api-key: sk-552e4dda91774b7cb0fc73b4ffbf97d8
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      max-tokens: 2000
      temperature: 0.7
    streaming-chat-model:
      api-key: sk-552e4dda91774b7cb0fc73b4ffbf97d8
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      max-tokens: 2000
      temperature: 0.7      

# ====== ⬇️【在这里配置你申请的高德API KEY】⬇️ ======
amap:
  api-key: ad8cc5d37d1beee96ab3ee0c75a6d816
